jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
      - uses: "actions/checkout@v1"
      - uses: "actions/setup-haskell@v1"
        with:
          cabal-version: "3.0"
          ghc-version: "8.8.1"
      - name: "Install Futhark"
        run: |
          cabal update
          cd "$(mktemp -d /tmp/futhark-XXX)"
          cabal install futhark --constraint='megaparsec < 8.0.0'
      - name: "Check Futhark"
        run: |
          export PATH=$HOME/.cabal/bin:$PATH
          futhark check information.fut
name: "Futhark CI"
on:
  - push
